name: find_it
description: A new Flutter application.

#version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+8
  cloud_firestore: ^0.12.5+2
  cached_network_image: ^1.1.1
  flutter_swiper: ^1.1.6
  snaplist: ^0.1.8
  location: ^2.3.5
  geolocator: ^5.1.1+1
  flutter_rating_bar: ^1.3.0+1
  dio: ^2.1.13
  sortedmap: ^0.4.2
  url_launcher: ^5.1.2
  firebase_auth: ^0.14.0+2
  dropdown_formfield: ^0.1.0
  firebase_storage: ^3.0.3
  image_picker: ^0.6.1+3




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
